{
 "title": "Ultron v2 Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "plan",
    "query": "show tag values with key=\"plan\""
   },
   {
    "name": "attacker",
    "query": "show tag values with key=\"attacker\""
   }
  ]
 },
 "panels": [
  {
   "title": "Successes@$attacker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "repeat": "attacker",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "report",
     "query": "SELECT last(\"success\") FROM \"report\" WHERE (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval), \"attacker\" fill(null)",
     "select": [
      [
       { "params": [ "successes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "Failures@$attacker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "repeat": "attacker",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "report",
     "select": [
      [
       { "params": [ "failures" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Ratio@$attacker",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "repeat": "attacker",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "report",
     "select": [
      [
       { "params": [ "failure_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "Successes@$attacker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "report",
     "query": "SELECT last(\"success\") FROM \"report\" WHERE (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval), \"attacker\" fill(null)",
     "select": [
      [
       { "params": [ "successes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "Failures@$attacker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "report",
     "select": [
      [
       { "params": [ "failures" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "Failure Ratio@$attacker",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "report",
     "select": [
      [
       { "params": [ "failure_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Attack Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Response Time(ms)" }
   ],
   "targets": [
    {
     "alias": "$tag_attacker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "result",
     "query": "SELECT mean(\"response_time\") FROM \"success\" WHERE $timeFilter GROUP BY time($__interval), \"api\" fill(null)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    },
    {
     "alias": "$tag_attacker->avg",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "success",
     "query": "SELECT mean(\"response_time\") FROM \"result\" WHERE  (\"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time(10s), \"attacker\" fill(null)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Total Transaction Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Transaction Per Second (TPS)" }
   ],
   "targets": [
    {
     "alias": "$tag_attacker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "report",
     "query": "SELECT mean(\"qps\") FROM \"report\" WHERE $timeFilter GROUP BY time($__interval), \"api\" fill(null)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "TP50",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_attacker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "report",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "TP90",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_attacker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "report",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "TP95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_attacker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "report",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "TP99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_attacker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "attacker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "report",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "attacker", "operator": "=~", "value": "/^$attacker$/" }
     ]
    }
   ]
  },
  {
   "title": "Attack Response Time@$attacker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "repeat": "attacker",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "TP50",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "report",
     "query": "SELECT last(\"TP50\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "api", "operator": "=~", "value": "/^$api$/" }
     ]
    },
    {
     "alias": "TP90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"TP90\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TP95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"TP95\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TP99",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"TP99\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Attack Response Time@$attacker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "TP50",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "report",
     "query": "SELECT last(\"TP50\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "api", "operator": "=~", "value": "/^$api$/" }
     ]
    },
    {
     "alias": "TP90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"TP90\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TP95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"TP95\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "TP99",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"TP99\") FROM \"report\" WHERE  (\"plan\" =~ /^$plan$/ AND \"attacker\" =~ /^$attacker$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}