// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ultron.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event_Type int32

const (
	Event_PING           Event_Type = 0
	Event_CONNECTED      Event_Type = 1
	Event_DISCONNECTED   Event_Type = 2
	Event_JOB_STARTED    Event_Type = 10
	Event_JOB_FINISHED   Event_Type = 11
	Event_REFRESH_CONFIG Event_Type = 20
)

// Enum value maps for Event_Type.
var (
	Event_Type_name = map[int32]string{
		0:  "PING",
		1:  "CONNECTED",
		2:  "DISCONNECTED",
		10: "JOB_STARTED",
		11: "JOB_FINISHED",
		20: "REFRESH_CONFIG",
	}
	Event_Type_value = map[string]int32{
		"PING":           0,
		"CONNECTED":      1,
		"DISCONNECTED":   2,
		"JOB_STARTED":    10,
		"JOB_FINISHED":   11,
		"REFRESH_CONFIG": 20,
	}
)

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}

func (x Event_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_ultron_proto_enumTypes[0].Descriptor()
}

func (Event_Type) Type() protoreflect.EnumType {
	return &file_ultron_proto_enumTypes[0]
}

func (x Event_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Type.Descriptor instead.
func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return file_ultron_proto_rawDescGZIP(), []int{1, 0}
}

type ReportResult_Result int32

const (
	ReportResult_ACCEPTED      ReportResult_Result = 0
	ReportResult_BATCH_EXPIRED ReportResult_Result = 1
	ReportResult_UNKNOWN_JOB   ReportResult_Result = 2
	ReportResult_UNKNOWN_BATCH ReportResult_Result = 3
)

// Enum value maps for ReportResult_Result.
var (
	ReportResult_Result_name = map[int32]string{
		0: "ACCEPTED",
		1: "BATCH_EXPIRED",
		2: "UNKNOWN_JOB",
		3: "UNKNOWN_BATCH",
	}
	ReportResult_Result_value = map[string]int32{
		"ACCEPTED":      0,
		"BATCH_EXPIRED": 1,
		"UNKNOWN_JOB":   2,
		"UNKNOWN_BATCH": 3,
	}
)

func (x ReportResult_Result) Enum() *ReportResult_Result {
	p := new(ReportResult_Result)
	*p = x
	return p
}

func (x ReportResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_ultron_proto_enumTypes[1].Descriptor()
}

func (ReportResult_Result) Type() protoreflect.EnumType {
	return &file_ultron_proto_enumTypes[1]
}

func (x ReportResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportResult_Result.Descriptor instead.
func (ReportResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_ultron_proto_rawDescGZIP(), []int{4, 0}
}

type SlaveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SlaveInfo) Reset() {
	*x = SlaveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ultron_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlaveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveInfo) ProtoMessage() {}

func (x *SlaveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ultron_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveInfo.ProtoReflect.Descriptor instead.
func (*SlaveInfo) Descriptor() ([]byte, []int) {
	return file_ultron_proto_rawDescGZIP(), []int{0}
}

func (x *SlaveInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SlaveInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Event_Type `protobuf:"varint,1,opt,name=type,proto3,enum=wosai.ultron.Event_Type" json:"type,omitempty"`
	// Types that are assignable to Data:
	//	*Event_StageConfig
	Data isEvent_Data `protobuf_oneof:"data"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ultron_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ultron_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ultron_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() Event_Type {
	if x != nil {
		return x.Type
	}
	return Event_PING
}

func (m *Event) GetData() isEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Event) GetStageConfig() *StageConfig {
	if x, ok := x.GetData().(*Event_StageConfig); ok {
		return x.StageConfig
	}
	return nil
}

type isEvent_Data interface {
	isEvent_Data()
}

type Event_StageConfig struct {
	StageConfig *StageConfig `protobuf:"bytes,2,opt,name=stage_config,json=stageConfig,proto3,oneof"`
}

func (*Event_StageConfig) isEvent_Data() {}

type StageConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Concurrence uint32 `protobuf:"varint,2,opt,name=concurrence,proto3" json:"concurrence,omitempty"`
	HatchRate   int32  `protobuf:"varint,3,opt,name=hatch_rate,json=hatchRate,proto3" json:"hatch_rate,omitempty"`
}

func (x *StageConfig) Reset() {
	*x = StageConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ultron_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageConfig) ProtoMessage() {}

func (x *StageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ultron_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageConfig.ProtoReflect.Descriptor instead.
func (*StageConfig) Descriptor() ([]byte, []int) {
	return file_ultron_proto_rawDescGZIP(), []int{2}
}

func (x *StageConfig) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StageConfig) GetConcurrence() uint32 {
	if x != nil {
		return x.Concurrence
	}
	return 0
}

func (x *StageConfig) GetHatchRate() int32 {
	if x != nil {
		return x.HatchRate
	}
	return 0
}

type Report struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId   string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	BatchId string `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
}

func (x *Report) Reset() {
	*x = Report{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ultron_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_ultron_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_ultron_proto_rawDescGZIP(), []int{3}
}

func (x *Report) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Report) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type ReportResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId   string              `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	BatchId string              `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Result  ReportResult_Result `protobuf:"varint,3,opt,name=result,proto3,enum=wosai.ultron.ReportResult_Result" json:"result,omitempty"`
}

func (x *ReportResult) Reset() {
	*x = ReportResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ultron_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResult) ProtoMessage() {}

func (x *ReportResult) ProtoReflect() protoreflect.Message {
	mi := &file_ultron_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResult.ProtoReflect.Descriptor instead.
func (*ReportResult) Descriptor() ([]byte, []int) {
	return file_ultron_proto_rawDescGZIP(), []int{4}
}

func (x *ReportResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportResult) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ReportResult) GetResult() ReportResult_Result {
	if x != nil {
		return x.Result
	}
	return ReportResult_ACCEPTED
}

var File_ultron_proto protoreflect.FileDescriptor

var file_ultron_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x77, 0x6f, 0x73, 0x61, 0x69, 0x2e, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x09,
	0x53, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0xe7, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x77, 0x6f,
	0x73, 0x61, 0x69, 0x2e, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x77, 0x6f, 0x73, 0x61, 0x69, 0x2e, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0b,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x68, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c,
	0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0f,
	0x0a, 0x0b, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x0a, 0x12,
	0x10, 0x0a, 0x0c, 0x4a, 0x4f, 0x42, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10,
	0x0b, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x46, 0x52, 0x45, 0x53, 0x48, 0x5f, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x47, 0x10, 0x14, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x65, 0x0a,
	0x0b, 0x53, 0x74, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x15, 0x0a, 0x06,
	0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f,
	0x62, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x68, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x15,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64,
	0x22, 0xca, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x77, 0x6f, 0x73, 0x61, 0x69, 0x2e, 0x75, 0x6c, 0x74, 0x72,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4d,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x43, 0x45,
	0x50, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x41, 0x54, 0x43, 0x48, 0x5f,
	0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x4a, 0x4f, 0x42, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x42, 0x41, 0x54, 0x43, 0x48, 0x10, 0x03, 0x32, 0x8c, 0x01,
	0x0a, 0x0d, 0x55, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3d, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x17, 0x2e, 0x77,
	0x6f, 0x73, 0x61, 0x69, 0x2e, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x53, 0x6c, 0x61, 0x76,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x13, 0x2e, 0x77, 0x6f, 0x73, 0x61, 0x69, 0x2e, 0x75, 0x6c,
	0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3c,
	0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x70, 0x12, 0x14, 0x2e, 0x77, 0x6f, 0x73, 0x61, 0x69,
	0x2e, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x1a,
	0x2e, 0x77, 0x6f, 0x73, 0x61, 0x69, 0x2e, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x73, 0x61, 0x69,
	0x2f, 0x75, 0x6c, 0x74, 0x72, 0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ultron_proto_rawDescOnce sync.Once
	file_ultron_proto_rawDescData = file_ultron_proto_rawDesc
)

func file_ultron_proto_rawDescGZIP() []byte {
	file_ultron_proto_rawDescOnce.Do(func() {
		file_ultron_proto_rawDescData = protoimpl.X.CompressGZIP(file_ultron_proto_rawDescData)
	})
	return file_ultron_proto_rawDescData
}

var file_ultron_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ultron_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ultron_proto_goTypes = []interface{}{
	(Event_Type)(0),          // 0: wosai.ultron.Event.Type
	(ReportResult_Result)(0), // 1: wosai.ultron.ReportResult.Result
	(*SlaveInfo)(nil),        // 2: wosai.ultron.SlaveInfo
	(*Event)(nil),            // 3: wosai.ultron.Event
	(*StageConfig)(nil),      // 4: wosai.ultron.StageConfig
	(*Report)(nil),           // 5: wosai.ultron.Report
	(*ReportResult)(nil),     // 6: wosai.ultron.ReportResult
}
var file_ultron_proto_depIdxs = []int32{
	0, // 0: wosai.ultron.Event.type:type_name -> wosai.ultron.Event.Type
	4, // 1: wosai.ultron.Event.stage_config:type_name -> wosai.ultron.StageConfig
	1, // 2: wosai.ultron.ReportResult.result:type_name -> wosai.ultron.ReportResult.Result
	2, // 3: wosai.ultron.UltronService.Subscribe:input_type -> wosai.ultron.SlaveInfo
	5, // 4: wosai.ultron.UltronService.SendUp:input_type -> wosai.ultron.Report
	3, // 5: wosai.ultron.UltronService.Subscribe:output_type -> wosai.ultron.Event
	6, // 6: wosai.ultron.UltronService.SendUp:output_type -> wosai.ultron.ReportResult
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ultron_proto_init() }
func file_ultron_proto_init() {
	if File_ultron_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ultron_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlaveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ultron_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ultron_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ultron_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Report); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ultron_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ultron_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Event_StageConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ultron_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ultron_proto_goTypes,
		DependencyIndexes: file_ultron_proto_depIdxs,
		EnumInfos:         file_ultron_proto_enumTypes,
		MessageInfos:      file_ultron_proto_msgTypes,
	}.Build()
	File_ultron_proto = out.File
	file_ultron_proto_rawDesc = nil
	file_ultron_proto_goTypes = nil
	file_ultron_proto_depIdxs = nil
}
